name:                checkers
version:             0.1.0.0
github:              "aabusang/checkers"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/checkers#readme>

dependencies:
- base >= 4.7 && < 5
- gloss >= 1.13
- random

ghc-options:
- -Wall
- -Wcompat

library:
  source-dirs: src
  other-modules:
    - Paths_checkers

executables:
  checkers-exe:
    main:                Main.hs
    source-dirs:         app
    other-modules:
    - Paths_checkers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - checkers

tests:
  checkers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - checkers
